spring:
  application:
    name: movie-ticket-booking-system

  datasource:
    url: jdbc:postgresql://localhost:5432/movie_booking_db
    username: root
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
